name: aoc2022
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: ^3.1.0
dependencies:
  args: ^2.3.1
  collection: ^1.17.0
